POST http://localhost:3000/login/ 
Content-Type: application/json

{
  "username": "christopher_phillips",
  "password": "christy@123"
}

###

GET http://localhost:3000/states/:stateId/
Content-Type: application/jsons

###

PUT http://localhost:3000/districts/
Content-Type: application/json

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}

###
GET http://localhost:3000/districts/:districtId/
Content-Type: application/json

###


DELETE http://localhost:3000/districts/:districtId/
Content-Type: application/json
